# Generated by Django 4.2.24 on 2025-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_quote_weight_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Комментарий модератора или ИИ о причине отказа/одобрения.', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.BooleanField(blank=True, default=None, help_text='Статус модерации: True — одобрено, False — отклонено, None — ещё не проверено.', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(error_messages={'unique': 'Такая цитата уже есть в базе.'}, unique=True),
        ),
    ]
